### ISSUE TITLE
julia2nix takes a long time

### ISSUE THREAD

**Issue by jtrakk** [thomasjm/julia2nix#5]
For a project with a lot of dependencies, `julia2nix` takes a long time. It would be nice if it could go faster. For example, as much as possible doing the work in parallel.

It might help to take inspiration from poetry2nix and rewrite `gather_packages.py` in Nix.

**Comment by thomasjm** [comment]
I'll look at `poetry2nix`, but this is currently modeled on `node2nix`. AFAIK such tools can't be written in Nix because they need to do impure network calls, primarily calling `nix-prefetch-git` to get sha256 hashes.

For now, please take a look at 4968f3c520ee93d6440adff9b88e374cf95c4e73, which adds parallelism. You can set the number of workers with a flag; it defaults to 8.

**Comment by jtrakk** [comment]
I think the way it works is that Manifest.toml/poetry.lock already knows the hash of the package so it can be downloaded in Nix as a fixed-output derivation. 

https://github.com/nix-community/poetry2nix/blob/master/mk-poetry-dep.nix#L77

**Comment by thomasjm** [comment]
Right, but already knowing the hash of the package is the tricky part. It might be possible with a modified git fetcher, given that we already know the git tree hash.

But anyway, let's keep discussion of a Nix rewrite to #3 . As far as perf goes, the parallelism made my sample project run go from ~1 minute to ~20 seconds in the current version. I'm going to close this since I don't think we can improve perf further with the current approach, but let's keep thinking about how to do it without `nix-prefetch-git` calls.
